### ISSUE TITLE
Animation for given points

### ISSUE THREAD

**Issue by ijontychie** [gruener-campus-malchow/simplescoreboard#1]

**Comment by lagees** [comment]
Zu anspruchsvoll, wenn man noch nie mit js,css oder html gearbeitet hat.

**Comment by Ovidios** [comment]
@lagees Hängt halt auch davon ab, was für eine Animation ihr euch vorstellt, muss ja auch mit @ijontychie abgesprochen werden, damit das vom Design her stimmig ist. Ich denke grundsätzlich, dass ihr einfache Animationen hinkriegen könntet!

**Comment by eintyp** [comment]
oh, fancy. kommt auf die todo liste.
