### ISSUE TITLE
Define events that can be triggered by remotes

### ISSUE THREAD

**Issue by nicolasraube** [gruener-campus-malchow/simplescoreboard#11]
- [ ] score ±1/2/4/5 for red/blue
- [ ] start/stop warning time for red/blue
- [ ] start/pause round
- [ ] next round
- [ ] new fight
- [ ] continue

**Comment by nicolasraube** [comment]
`{
'name': 'eventname',
'value': 0,
'team': 'red'
}`

**Comment by eintyp** [comment]
see issue #2
